### ISSUE TITLE
Template copy error

### ISSUE THREAD

**Issue by marlon-tucker** [mwootendev/generator-tslib-webpack#2]
Hello, 

I seem to be hitting the same error as described in this issue [here](https://github.com/yeoman/generator-polymer/issues/240) - that issue has been resolved so hopefully it should be simple to fix this generator as well.

Basically the `.gitignore` template file is being auto renamed by npm, and so it is not present in the published template, which makes the copy command fail.

**Comment by mwootendev** [comment]
Marlon,

I think I have a fix posted with version 1.0.1. I tried running the generator on a fresh install on Linux and it was successful. Let me know if you are still having any issues.

Thanks.

**Comment by marlon-tucker** [comment]
Hi, 

Yep all seems to be good :), thanks.
